### ISSUE TITLE
Epic2 with mm10/GRCm38

### ISSUE THREAD

**Issue by sagarutturkar** [biocore-ntnu/epic2#11]
How to run epic2 with mm10/GRCm38? I tried with `--genome mm10` but it did not work. I get an error as:

```
Traceback (most recent call last):
  File "/group/bioinfo/apps/apps/miniconda-4.3.21/envs/epic2-2018-Jan-03/bin/epic2", line 212, in <module>
    main()
  File "/group/bioinfo/apps/apps/miniconda-4.3.21/envs/epic2-2018-Jan-03/bin/epic2", line 182, in main
    effective_genome_length, chromsizes = egl_and_chromsizes(args)
  File "epic2/src/genome_info.pyx", line 189, in epic2.src.genome_info.egl_and_chromsizes
  File "epic2/src/genome_info.pyx", line 82, in epic2.src.genome_info.find_readlength
ValueError: invalid literal for int() with base 10: '-'
```

**Comment by endrebak** [comment]
Hi and thanks for reporting this. Could you try updating your version of epic2 and then see what happens?

```
pip install --no-cache-dir epic2
```

**Comment by sagarutturkar** [comment]
Thank you for the reply and newest version resolved the issue.

I have another question regarding the results. I did peak calling with MACS (PE BAM with MAPQ10) and epic2 (BEDPE files generated from the same BAM files). I get < 1000 broad peaks with MACS while epic2 generated > 50,000 peaks. I am not sure why there is such a huge difference.

**Comment by endrebak** [comment]
They are very different algorithms :) I was not happy with MACS2 for H3K27me3 at all, which is why I reimplemented SICER. It is impossible to answer your question more specifically without knowing more about the data and settings used, unfortunately. 

Feel free to reopen this issue or create another if you have further questions :)
