### ISSUE TITLE
Only changes with a positive log2FoldChange detected

### ISSUE THREAD

**Issue by lutsik** [biocore-ntnu/epic2#13]
I can only detect unidirectional changes when comparing ChIP data of histone marks between groups of 2-3 samples. This is reproducible across different marks of my data set, but I have not prepared a minimal example yet. Could you comment?

**Comment by endrebak** [comment]
log2FoldChange compares ChIP against input. If you have more input in a region, it is not interesting no? If you set FDR to 1 you should see these regions too.

Thanks for trying epic2 btw.

**Comment by endrebak** [comment]
Also, if you are comparing ChIP against ChIP, epic2-df (not working yet) is the algorithm developed for this. :)

**Comment by lutsik** [comment]
OK, thanks for the reply. You have to be careful with your terminology then. I would not use "Treatment" and "Control" terms, as this is confusing.

To be honest, given this limitation, it still worked quite OK. To get the regions changed oppositely I simply inverted the labels. I then merged the results of both runs with a simple script, looks legit.

Looking forward to epic2-df.

**Comment by endrebak** [comment]
Thanks for the feedback. I am mostly a programmer, not a biologist. I
should write a better description in the README at least :) I used the same
terms as https://github.com/dariober/SICERpy

Will send you a ping when I have finished epic-df. Working on it now :)

**Comment by endrebak** [comment]
`pip install epic2==0.0.26`. 

I've tested it on two datasets, it gives the same results as SICER.

epic2 will be out in bioinformatics in a month, please cite if you are using it for a publication :).

**Comment by lutsik** [comment]
ok, thanks! I will try it out. 

I will definitely add the citation once your paper is out (congrats!).

**Comment by endrebak** [comment]
Feel free to reopen or start a new thread if you have more questions :)
