### ISSUE TITLE
Using option "--gaps-allowed" causes error

### ISSUE THREAD

**Issue by keoughkath** [biocore-ntnu/epic2#15]
Hello,

When I use the option --gaps-allowed I get the error shown below. I've tried a few different values for --gaps-allowed and each result in the same error. 

**Command:**

`epic2 --treatment project/treatment.bam --control project/control.bam --genome hg38 --keep-duplicates --fragment-size 75 --bin-size 50000 --gaps-allowed 5 --output test_3.bed`

**Error:**

`Traceback (most recent call last):
  File "~/miniconda3/bin/epic2", line 217, in <module>
    _main(args)
  File "~/miniconda3/lib/python3.7/site-packages/epic2/main.py", line 46, in _main
    chip_count, args["bin_size"], effective_genome_length, args["gaps_allowed"] * args["bin_size"], args["e_value"])
  File "epic2/src/SICER_stats.pyx", line 385, in epic2.src.SICER_stats.compute_score_threshold
  File "epic2/src/SICER_stats.pyx", line 221, in epic2.src.SICER_stats.Background_island_probscore_statistics.find_island_threshold
  File "epic2/src/SICER_stats.pyx", line 168, in epic2.src.SICER_stats.Background_island_probscore_statistics.background_island_expectation
IndexError: list index out of range`

Thanks for looking into this! -Kathleen

**Comment by endrebak** [comment]
I will look into it :) Thanks for reporting :)

**Comment by endrebak** [comment]
Note to self: set up tests that ensure that the epic2 does not fail when run with legal input values.

**Comment by endrebak** [comment]
I have not been able to reproduce this. Are you using `0.0.29`?j

**Comment by keoughkath** [comment]
I'm using `0.0.26` installed with [conda](https://anaconda.org/bioconda/epic2), but I will install that version and give it a try :)

**Comment by endrebak** [comment]
Forgot to update on conda. Will do when I am back :)

**Comment by keoughkath** [comment]
I'm not able to install `v0.0.29` with pip, but `v0.0.28` produces the same error for me. I tried it with the test files though and those run fine, so I'm checking my input files to see if there's something weird there.

**Comment by endrebak** [comment]
Different chromnames than in UCSC might be it?

**Comment by keoughkath** [comment]
No, they're the same ('chr1' etc.)

**Comment by keoughkath** [comment]
I think it might have something to do with self.window_score since the error indicates a list indexing issue stemming from line 176 of SICER_stats.pyx.

**Comment by endrebak** [comment]
If you can share the data it would likely be easy for me to debug. A
private link to google drive or something perhaps?

**Comment by keoughkath** [comment]
Will do! Can I send to your email?

**Comment by endrebak** [comment]
Can you try with the flag —experimental-statistics in 0.0.29?

Try to Install it with

pip install —no-cache-dir epic2==0.0.29

:)

Eager to hear if it worked

**Comment by endrebak** [comment]
Yes, but I do not have access to a computer before Monday. Please try
0.0.29 first :)

**Comment by endrebak** [comment]
I consider it very likely that this due to a bug in the original SICER
algorithm that was fixed with the 0.0.29 flag —experimental-statistics.
SICER precomputed some stats function for you to save time. However it did
not precompute an inf number of values so it fails on large datasets.
Remember SICER was made in 2008 or so :)

**Comment by endrebak** [comment]
https://pypi.org/project/epic2/#files

0.0.29 is out on pypi so it’s weird you cannot dl it :)

**Comment by keoughkath** [comment]
Looks like the install issue was because my conda version was fighting with pip, gah. Fixed that and it installed ok. The `--experimental-statistics` flag works! Thanks!! Closing now :)

**Comment by endrebak** [comment]
Yaaay!
