### ISSUE TITLE
epic2-df ValueError: No objects to concatenate

### ISSUE THREAD

**Issue by naity** [biocore-ntnu/epic2#16]
Hi there,

I'm trying to replicate the example of epic2-df but got this error: `ValueError: No objects to concatenate`. Please see the complete output below. Thank you very much!

```
Running epic2 on KO.
Found a median readlength of 25.0

Using genome hg19.

Using an effective genome length of ~2510 * 1e6

Parsing ChIP file(s):
  ./examples/test.bam

Valid ChIP reads: 9904 (9924 before out of bounds removal)

Score threshold: 7.146

Number of tags in a window: 1

Number of islands found: 166

Empirical estimate of FDR is: 1.0 (1000/166)
Running epic2 on WT.
Found a median readlength of 25.0

Using genome hg19.

Using an effective genome length of ~2510 * 1e6

Parsing ChIP file(s):
  ./examples/control.bam

Valid ChIP reads: 9290 (9310 before out of bounds removal)

Score threshold: 7.21

Number of tags in a window: 1

Number of islands found: 48

Empirical estimate of FDR is: 1.0 (1000/48)
Comparing islands.
Traceback (most recent call last):
  File "/home/ytian/anaconda3/envs/epic2/bin/epic2-df", line 370, in <module>
    [pd.Series(arr) for _, arr in natsorted(ko_counts.items())])
  File "/home/ytian/anaconda3/envs/epic2/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 228, in concat
    copy=copy, sort=sort)
  File "/home/ytian/anaconda3/envs/epic2/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 262, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
```

**Comment by endrebak** [comment]
Thanks for reporting. Will try to reproduce Monday :)

**Comment by endrebak** [comment]
The error was due to pyranges, not epic2. Should be fixed now.

Could you please try `pip install --no-cache-dir epic2`? And if that does not work, `pip install --no-cache-dir pyranges`?

**Comment by naity** [comment]
Yes, that resolved the issue. Thank you!

**Comment by Victor21v** [comment]
Hello,

Just got an error on version 0.0.33

Valid ChIP reads: 16418480 (16435005 before out of bounds removal)
 
Traceback (most recent call last):
  File "/home/usuario/anaconda3/bin/epic2-df", line 332, in <module>
    bins_counts_ko = _main(args)
  File "/home/usuario/anaconda3/lib/python3.6/site-packages/epic2/main.py", line 47, in _main
    if args["original_statistics"]:
KeyError: 'original_statistics'

Thanks!

**Comment by Victor21v** [comment]
Now I have updated pyranges from bioconda and epic2-df displays a different error:

"Traceback (most recent call last):
  File "/home/usuario/anaconda3/bin/epic2-df", line 12, in <module>
    from recordclass import recordclass
ModuleNotFoundError: No module named 'recordclass'"

**Comment by endrebak** [comment]
I will fix it. Thanks. See #18 :)

**Comment by endrebak** [comment]
Now 0.0.34 is out. It is out on PyPI now and conda later today.
