### ISSUE TITLE
Install from source or w/o conda 

### ISSUE THREAD

**Issue by whositwhatnow** [biocore-ntnu/epic2#17]
Hello,

I want to install this on our local clusterbut we do not use conda as installer.  Can this be installed without conda.

**Comment by endrebak** [comment]
Thanks for your interest :)

What happens if you try `pip install epic2`? I never have tried installing it without conda, but I think it is 99.999% it will fail. But I would be interested in seeing your error message :)

I will try to find a fix for this :)

**Comment by whositwhatnow** [comment]
# pip3.6 install epic2
Collecting epic2
  Using cached https://files.pythonhosted.org/packages/48/a6/add5742fc7b644a972288753902da44725c76cdc606575330d627fd6e7eb/epic2-0.0.30.tar.gz
    Complete output from command python setup.py egg_info:
    which: no conda in (/cm/shared/apps/python/3.6.2/bin:/cm/local/apps/cluster-tools/bin:/cm/local/apps/cmd/sbin:/cm/local/apps/cmd/bin:/cm/shared/apps/cmgui:/cm/shared/apps/slurm/16.05.8/sbin:/cm/shared/apps/slurm/16.05.8/bin:/sbin:/bin:/usr/sbin:/usr/bin:/cm/local/apps/environment-modules/3.2.10/bin:/opt/dell/srvadmin/bin:/opt/dell/srvadmin/sbin)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ol6jxb58/epic2/setup.py", line 42, in <module>
        conda_path = check_output("which conda", shell=True).decode().strip()
      File "/cm/shared/apps/python/3.6.2/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/cm/shared/apps/python/3.6.2/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command 'which conda' returned non-zero exit status 1.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ol6jxb58/epic2/

**Comment by endrebak** [comment]
Try `pip install epic2==0.0.32`. This is not a fix, but should give a more informative error message that I would like you to post here :)

**Comment by whositwhatnow** [comment]
pip3.6 install epic2==0.0.32
Collecting epic2==0.0.32
  Could not find a version that satisfies the requirement epic2==0.0.32 (from versions: 0.0.1, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27, 0.0.28, 0.0.29, 0.0.30)
No matching distribution found for epic2==0.0.32

**Comment by endrebak** [comment]
Ah, you were too quick. It should be there in a second :)

**Comment by whositwhatnow** [comment]
Looks to have installed no errors.

pip3.6 install epic2==0.0.32
Collecting epic2==0.0.32
  Using cached https://files.pythonhosted.org/packages/70/a8/f488c6b626656933686999d60517b83b1e8828d7369c786acd2304b8d7e6/epic2-0.0.32.tar.gz
Requirement already satisfied: scipy in /cm/shared/apps/python/3.6.2/lib/python3.6/site-packages (from epic2==0.0.32) (0.19.1)
Requirement already satisfied: numpy in /cm/shared/apps/python/3.6.2/lib/python3.6/site-packages (from epic2==0.0.32) (1.14.2)
Collecting natsort (from epic2==0.0.32)
  Using cached https://files.pythonhosted.org/packages/e7/13/a66bfa0ebf00e17778ca0319d081be686a33384d1f612fc8e0fc542ac5d8/natsort-6.0.0-py2.py3-none-any.whl
Requirement already satisfied: cython in /cm/shared/apps/python/3.6.2/lib/python3.6/site-packages (from epic2==0.0.32) (0.29.6)
Requirement already satisfied: pysam in /cm/shared/apps/python/3.6.2/lib/python3.6/site-packages (from epic2==0.0.32) (0.15.1)
Collecting pandas (from epic2==0.0.32)
  Downloading https://files.pythonhosted.org/packages/19/74/e50234bc82c553fecdbd566d8650801e3fe2d6d8c8d940638e3d8a7c5522/pandas-0.24.2-cp36-cp36m-manylinux1_x86_64.whl (10.1MB)
    100% |████████████████████████████████| 10.1MB 4.7MB/s 
Collecting pyranges>=0.0.27 (from epic2==0.0.32)
  Downloading https://files.pythonhosted.org/packages/29/76/233d855872bc916b8549b26c505c7fdadfb57e7f824c739fa093fe37fcec/pyranges-0.0.30.tar.gz (431kB)
    100% |████████████████████████████████| 440kB 52.8MB/s 
Requirement already satisfied: python-dateutil>=2.5.0 in /cm/shared/apps/python/3.6.2/lib/python3.6/site-packages (from pandas->epic2==0.0.32) (2.6.1)
Requirement already satisfied: pytz>=2011k in /cm/shared/apps/python/3.6.2/lib/python3.6/site-packages (from pandas->epic2==0.0.32) (2017.2)
Collecting ncls (from pyranges>=0.0.27->epic2==0.0.32)
  Downloading https://files.pythonhosted.org/packages/f7/08/156506261f4c3426191dc4fb8bbc45f9657067a2458e6aea588bc264ae07/ncls-0.0.42.tar.gz (621kB)
    100% |████████████████████████████████| 624kB 41.6MB/s 
Collecting tabulate (from pyranges>=0.0.27->epic2==0.0.32)
  Downloading https://files.pythonhosted.org/packages/c2/fd/202954b3f0eb896c53b7b6f07390851b1fd2ca84aa95880d7ae4f434c4ac/tabulate-0.8.3.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 39.2MB/s 
Collecting sorted_nearest (from pyranges>=0.0.27->epic2==0.0.32)
  Downloading https://files.pythonhosted.org/packages/af/5b/4fb6f94b513551e755aaa19dabfd1816ba5d2c5af4cb1e1c78729bd75f69/sorted_nearest-0.0.15-cp36-cp36m-manylinux1_x86_64.whl (493kB)
    100% |████████████████████████████████| 501kB 49.1MB/s 
Collecting pyrle (from pyranges>=0.0.27->epic2==0.0.32)
  Downloading https://files.pythonhosted.org/packages/a7/80/dc4653b55dfe775b15aa3943d957d6140b87e28e43f7a0f041e8bbe1e8c4/pyrle-0.0.22-cp36-cp36m-manylinux1_x86_64.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 33.9MB/s 
Collecting bamread (from pyranges>=0.0.27->epic2==0.0.32)
  Downloading https://files.pythonhosted.org/packages/bb/d3/6348db074b4be772e728b79e4235cb0e5af02ead7762e91c694bf49ee497/bamread-0.0.3.tar.gz (108kB)
    100% |████████████████████████████████| 112kB 56.7MB/s 
Requirement already satisfied: pybigwig in /cm/shared/apps/python/3.6.2/lib/python3.6/site-packages (from pyranges>=0.0.27->epic2==0.0.32) (0.3.13)
Collecting piedpiper (from pyranges>=0.0.27->epic2==0.0.32)
  Downloading https://files.pythonhosted.org/packages/96/a9/8b5c0107447c8cbf75e18afd3232fbb71f150614db01bdbf792b8d92625b/piedpiper-0.0.2.tar.gz
Requirement already satisfied: six>=1.5 in /cm/shared/apps/python/3.6.2/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas->epic2==0.0.32) (1.11.0)
Installing collected packages: natsort, pandas, ncls, tabulate, sorted-nearest, pyrle, bamread, piedpiper, pyranges, epic2
  Running setup.py install for ncls ... done
  Running setup.py install for tabulate ... done
  Running setup.py install for bamread ... done
  Running setup.py install for piedpiper ... done
  Running setup.py install for pyranges ... done
  Running setup.py install for epic2 ... done
Successfully installed bamread-0.0.3 epic2-0.0.32 natsort-6.0.0 ncls-0.0.42 pandas-0.24.2 piedpiper-0.0.2 pyranges-0.0.30 pyrle-0.0.22 sorted-nearest-0.0.15 tabulate-0.8.3

**Comment by endrebak** [comment]
Weird. 

If you do 

`epic2 -ex
`
you should see an example command you can test. 

1) Does it work? 

2) Does epic2 work with bam files?

**Comment by whositwhatnow** [comment]
epic2 -t /cm/shared/apps/python/3.6.2/lib/python3.6/site-packages/epic2/examples/test.bed.gz -c /cm/shared/apps/python/3.6.2/lib/python3.6/site-packages/epic2/examples/control.bed.gz > deleteme.txt
Found a median readlength of 25.0

Using genome hg19.

Using an effective genome length of ~2510 * 1e6

Parsing ChIP file(s):
  /cm/shared/apps/python/3.6.2/lib/python3.6/site-packages/epic2/examples/test.bed.gz

Valid ChIP reads: 9904 (9924 before out of bounds removal)

Score threshold: 7.146

Number of tags in a window: 1

Number of islands found: 166

Parsing Input file(s):
  /cm/shared/apps/python/3.6.2/lib/python3.6/site-packages/epic2/examples/control.bed.gz

Valid Background reads: 9290 (9310 before out of bounds removal)



________________________________

**Comment by whositwhatnow** [comment]
I’m going to test with bam files shortly.

Email sent from my phone.
________________________________

**Comment by endrebak** [comment]
I am building wheels (prebuilt binaries for Python) from now on anyways, so then it should be guaranteed to work using only pip :)

**Comment by endrebak** [comment]
No need to check bam for my sake, but tell me if you encounter any weirdness.

**Comment by whositwhatnow** [comment]
Ok excellent thanks for the quick response / help!!

Email sent from my phone.
________________________________
