### ISSUE TITLE
epic2-df eror on version 0.0.33

### ISSUE THREAD

**Issue by Victor21v** [biocore-ntnu/epic2#18]
Hello,

Just got an error on version 0.0.33. I get this error either with or without --experimental-statistics. It seems to me like --experimental-statistics is not working properly as the error doesn't change at all. I have used BEDPE format

Valid ChIP reads: 16418480 (16435005 before out of bounds removal)

Traceback (most recent call last):
File "/home/usuario/anaconda3/bin/epic2-df", line 332, in
bins_counts_ko = _main(args)
File "/home/usuario/anaconda3/lib/python3.6/site-packages/epic2/main.py", line 47, in _main
if args["original_statistics"]:
KeyError: 'original_statistics'

Thanks!

**Comment by endrebak** [comment]
Thanks, will fix first thing tomorrow :)

**Comment by endrebak** [comment]
Fixed in 0.0.34. Thanks!
