### ISSUE TITLE
epic2-df, module error and version

### ISSUE THREAD

**Issue by mpaya** [biocore-ntnu/epic2#19]
Hi, I just found about `epic2-df` and wanted to test it by seeing the help but had this error (both on 0.0.26 and 0.0.34):
```
epic2-df -h
Traceback (most recent call last):
  File "/home/bioinf/software/anaconda3/bin/epic2-df", line 12, in <module>
    from recordclass import recordclass
ModuleNotFoundError: No module named 'recordclass'
```
This is fixed with `pip install recordclass`, but would be nice if this was installed along `epic2`. 

Next I wanted to see if version of `epic2-df` would be the same or different to that of epic2, but the option `epic2-df -v` is not there. I'd suggest adding it. :)
Cheers

**Comment by endrebak** [comment]
Fixing right now, that is an unused dependency. Also adding version-flags. Hoping to get `epic2-bw` out tomorrow too.

**Comment by endrebak** [comment]
Should be fixed in `0.0.35` on pip. Working for you too?

**Comment by mpaya** [comment]
Working here too both things. :)

**Comment by endrebak** [comment]
Conda-update on the way: https://github.com/bioconda/bioconda-recipes/pull/15705
