### ISSUE TITLE
error st::bad_alloc

### ISSUE THREAD

**Issue by coraliegimonnet** [biocore-ntnu/epic2#23]
I would like to use epic2 on my chip seq dataset but i have an error. I have the same when i run the example :

epic2 -t /usr/local/lib/python3.7/dist-packages/epic2/examples/test.bed.gz -c /usr/local/lib/python3.7/dist-packages/epic2/examples/control.bed.gz > deleteme.txt 
Found a median readlength of 25.0

Using genome hg19.

Using an effective genome length of ~2510 * 1e6

Parsing ChIP file(s): /usr/local/lib/python3.7/dist-packages/epic2/examples/test.bed.gz terminate called after throwing an instance of 'std::bad_alloc' 
what(): std::bad_alloc 
Abandon

Do you have any idea what's wrong?

Thanks

**Comment by endrebak** [comment]
What system do you use? What is your gcc version? What is your epic2
version? Did you install from conda or pip? Does it work if you unzip the
files first?

Thanks for reporting, I would love to get to the bottom of this :)
