### ISSUE TITLE
paired-end bam input

### ISSUE THREAD

**Issue by crazyhottommy** [biocore-ntnu/epic2#24]
Hi,

trying out epic2.
reading the --help and see if bam format only single-end is supported? or I should convert the paired-end bam to bedpe?

Thanks!
Tommy

**Comment by endrebak** [comment]
It does not support paired-end BAM yet, you need to convert to bedpe. I
should find out how to use pysam for PE both for Pyranges and epic2, but
when that will be I do not know :/

**Comment by alnfedorov** [comment]
@endrebak, +1. This feature would be really handy. 
In case someone is stumbled on this thread, here is what I used as a workaround.
```py3
import tempfile
from asyncio.subprocess import create_subprocess_shell
async def bam_to_bedpe(bam: str, saveto: str = None, threads: int = 1) -> str:
    assert threads >= 1
    saveto = saveto if saveto else tempfile.mkstemp()[1]
    cmd = f"sambamba sort -t {threads} -p -n -M {bam} -o /dev/stdout | " \
          f"samtools fixmate --threads {threads} -r -O bam /dev/stdin /dev/stdout | " \
          f"bedtools bamtobed -i /dev/stdin -bedpe > {saveto}"
    process = await create_subprocess_shell(cmd, stderr=sys.stdout)
    assert await process.wait() == 0
    assert os.path.exists(saveto)
    return saveto


```

**Comment by endrebak** [comment]
I want to fix this. Will try to do so in a month or two. Busily writing up PhD now :)
