### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by balwierz** [biocore-ntnu/epic2#25]
I think it is the same error as in (now closed) #23 
Within a minute of executing epic2 the program is terminated. 

```
Found a median readlength of 156.5
 
Using genome hg19.
 
Using an effective genome length of ~1237 * 1e6
 
Parsing ChIP file(s): 
  mySample.bedpe 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

The machine itself has 200+GB of available RAM.

The command line is:
```
/usr/bin/python2 /usr/local/bin/epic2 --treatment mySample.bedpe --control myBg.bedpe --keep-duplicates --chromsizes danRer10/chromInfo.sorted.txt --bin-size 100 --output mySample
```

Note: The output says "genome hg19", which is wrong. Epic failed when I declared --genome danRer10 (why? It is an old genome, and is present in UCSC tables and download files for 5 years now). So I specified --chromsizes manually.

Installed from pip.
$ gcc --version
gcc (Debian 8.3.0-6) 8.3.0
$ python2 --version
Python 2.7.16

**Comment by endrebak** [comment]
Thank you. I will try to get to the bottom of it :) What is the epic2 version?

**Comment by balwierz** [comment]
$ epic2 --version
0.0.36

**Comment by endrebak** [comment]
I assume the bug is in the PE-code. I will try to reproduce :)

Thanks for reporting :)

**Comment by endrebak** [comment]
Would you be able to share the data, so that I can try to reproduce the bug (for example on google drive, private link)?

**Comment by balwierz** [comment]
I managed to reduce the file to one line (just the fist one). Specify foo.bedpe as both treatment and control for simplicity. Use the attached chromosome length file as well.

http://results.genereg.net/test/foo.bedpe
http://results.genereg.net/test/chromInfo.sorted.txt

**Comment by endrebak** [comment]
Thanks! I will download and start looking at it soon :)

**Comment by endrebak** [comment]
Works for me:

```
epic2 -t bug.bedpe -c bug.bedpe -cs genomes.txt
Found a median readlength of 0.0

Using genome hg19.

Using an effective genome length of ~1112 * 1e6

Parsing ChIP file(s):
  bug.bedpe

Valid ChIP reads: 1 (1 before out of bounds removal)

Score threshold: 0.001

Number of tags in a window: 1

Number of islands found: 1

Parsing Input file(s):
  bug.bedpe

Valid Background reads: 1 (1 before out of bounds removal)

#Chromosome	Start	End	PValue	Score	Strand	ChIPCount	InputCount	FDR	log2FoldChange
```

Do you have an opportunity to install conda with python 3 and get epic2 from bioconda? I really am sorry I could not be of more help.

**Comment by endrebak** [comment]
Also danrer10/danRer10 worked for me. I wonder if the problems are due to you using legacy Python?

```
epic2 -t bug.bedpe -c bug.bedpe -gn danRer10
Found a median readlength of 0.0

Using genome danRer10.

Using an effective genome length of ~1076 * 1e6

Parsing ChIP file(s):
  bug.bedpe

Valid ChIP reads: 1 (1 before out of bounds removal)

Score threshold: 0.001

Number of tags in a window: 1

Number of islands found: 1

Parsing Input file(s):
  bug.bedpe

Valid Background reads: 1 (1 before out of bounds removal)

#Chromosome	Start	End	PValue	Score	Strand	ChIPCount	InputCount	FDR	log2FoldChange
```

**Comment by endrebak** [comment]
Some small compilation changes in `epic2==0.0.39`. Might it work now?
