### ISSUE TITLE
how to discard more than one chromosomes with parameter -d

### ISSUE THREAD

**Issue by ShuangHe33** [biocore-ntnu/epic2#28]
Hi,
I want to exclude chrY and chrM in the input bam file, I tried to use parameter "-d chrY_chrM" ,  it seemed that it was not the appropriate format.

Thank you in advance!

**Comment by endrebak** [comment]
It uses regular regexes. -d «(chrM|chrY)» should work.

You can play around with regexes here:

https://rubular.com/

Endre

**Comment by endrebak** [comment]
https://rubular.com/r/CsPzEkIjAPoga4

Feel free to ask more questions if something is unclear :)

**Comment by ShuangHe33** [comment]
> https://rubular.com/r/CsPzEkIjAPoga4
> 
> Feel free to ask more questions if something is unclear :)

Thank you !  I have  another question : is the peak 1-based or 0-based?

**Comment by endrebak** [comment]
0-based :)
