### ISSUE TITLE
bedpe input not processed correctly

### ISSUE THREAD

**Issue by ptrebert** [biocore-ntnu/epic2#29]
Hi,
I am testing v.0.0.36 with paired-end reads (treatment plus control) for mouse.

In the output for my H3K4me3 test file, I see the following things...
1) `Using genome hg19`
Confusing; I specified the relevant chromosomes via `--chromosomes` and `effGenFraction`, so why is `epic2` telling me it's using `hg19` (and not, say, `custom genome`)? The effective genome length, however, seems to be correct, so this might simply be a misleading log output.

2) `Found a median readlength of 355.5`
This one evades me completely - the read length of the input data is 75, and I just computed the numbers myself on the bedpe file, giving a mean of 74.8 and a median of 75, as expected.

3) About half of the reads seem to be removed (out of bounds); this strikes me as odd, could this be linked to point 1. above?

Thanks for your help.

+Peter

**Comment by endrebak** [comment]
Thanks for reporting. I’ll look at it after the weekend :)

Is it possible for you to post the head of each file?

Endre

**Comment by endrebak** [comment]
1. Is a glitch I’ve noticed myself and should have fixed.

2. I use the start of the leftmost mate and end of the rightmost mate to
compute the lengths. Do you do it the same way?

3. Could you please post the complete log-output of your run, including the
command used and the content of the chromsizes file?

4. Do you have the opportunity to share the files with me on a private
Google-drive link? This would make debugging easier.

Endre

**Comment by ptrebert** [comment]
1. perfect
2. I see, that's a misunderstanding then (for me, this would be something like fragment length); but ok, not a problem.

Concerning the last part, I made a test run with single-end histone data (as BAM) combined with paired-end Input control (as BEDPE). All reads of the BAM are retained, but again, almost 50% of the BEDPE reads are out-of-bounds removed. The chromosome size file looks as follows:

```
chr1    195471971
chr2    182113224
chr3    160039680
chr4    156508116
chr5    151834684
chr6    149736546
chr7    145441459
chr8    129401213
chr9    124595110
chr10   130694993
chr11   122082543
chr12   120129022
chr13   120421639
chr14   124902244
chr15   104043685
chr16   98207768
chr17   94987271
chr18   90702639
chr19   61431566
```

The command line I use looks as follows:
`epic2 --keep-duplicates -fdr 0.1 --treatment {input.signal} --control {input.background} --chromsizes {input.chromosomes} --effective-genome-fraction {params.effgen_frac} --output {output}`

For single-end, the parameter `--fragment-size` is also set to the respective value. I use bedtools to convert from paired-end BAM to BEDPE as follows: `bedtools bamtobed -bedpe -mate1 -i {input.bam} | gzip > {output}`
If you still need the entire dataset, I can send a google drive link (to the email address I see in your comment above or do you prefer a different one?)

+Peter

**Comment by endrebak** [comment]
Answer to point: 2. Yours is the correct terminology. I guess I should
write "read length" for single-end and "mate pair length" for paired-end.

New remarks/questions:

1) Your genome seems to have shorter chromosomes so if hg19 were used you'd
have no fragments dropped. I have updated epic2 to use correct terminology
and say whether custom chromsizes were used or not (but I am not uploading
a new version to PyPI before I find the bug.)

2) Can you also please post the whole log so that I can see the "Valid
Background reads: 9290 (9310 before out of bounds removal)" part?

3) You could just grep the bedpe files for chr19 | shuf -n 10000, confirm
that the bug happens on those data too and then send them to me. Would be
easier for all of us :)

Thanks for your help and patience. I would love to get to the bottom of
this :)

**Comment by ptrebert** [comment]
The test dataset is in your mail

**Comment by endrebak** [comment]
Thanks! Wonderful. Will look at today :)

**Comment by endrebak** [comment]
I could reproduce :) So I should be able to get to the bottom of this :)

**Comment by endrebak** [comment]
The reason is that half of your lines have the leftmost mate on the right end.

Like so:

```
chrX   252        321        chrX   71        146        Name     11      -       +
```

This might be valid bedpe for all I know. In that case, I misunderstood the specification. Will read up on it :)

**Comment by endrebak** [comment]
epic2 0.0.37 is out on PyPI. Please test it and see if it works :)

```
epic2 -t test_set_signal.bedpe  -c test_set_control.bedpe -cs chromsizes.txt    > /dev/null
Found a median fragment size of 238.0

Using chromosome sizes found in chromsizes.txt.

Using an effective genome length of ~2221 * 1e6

Parsing ChIP file(s):
  test_set_signal.bedpe

Valid ChIP reads: 97392 (97392 before out of bounds removal)

Score threshold: 9.491

Number of tags in a window: 1

Number of islands found: 1628

Parsing Input file(s):
  test_set_control.bedpe

Valid Background reads: 99561 (99561 before out of bounds removal)
```

**Comment by ptrebert** [comment]
Thanks for releasing an updated version.
1. yes, because I produced the BEDPE files with the `-mate1` switch in bedtools as I wrote in my comment above. Depending on how you fixed `epic2` for that, as a user, I can live with any format restrictions for the input as long as this is clearly documented (or, at least, the tool throws an error for unexpected conditions).
2. I cannot test it myself now because of the following:

```
Traceback (most recent call last):

  File "/TL/epigenetics2/work/pebert/conda/envs/cse/bin/epic2", line 10, in <module>
    from epic2.main import _main
  File "/TL/epigenetics2/work/pebert/conda/envs/cse/lib/python3.6/site-packages/epic2/main.py", line 5, in <module>
    from epic2.src.reads_to_bins import files_to_bin_counts
  File "epic2/src/reads_to_bins.pyx", line 16, in init epic2.src.reads_to_bins
  File "libcalignedsegment.pxd", line 66, in init epic2.src.read_bam
ValueError: pysam.libcalignedsegment.PileupColumn size changed, may indicate binary incompatibility. Expected 88 from C header, got 72 from PyObject
```
Any ideas?

**Comment by endrebak** [comment]
Create a new conda environment and install epic2 there? The problem is most likely a htslib header mismatch.

**Comment by endrebak** [comment]
I have no format restrictions, but pick the leftmost start and rightmost end of bedpe files. This requires two ifs in the IO, but it should not change the read times much :)

**Comment by endrebak** [comment]
(I should perhaps write a small guide in the install section about installing epic2 in a new environ.)

**Comment by ptrebert** [comment]
Well, creating a new environment just for a fixed tool is hardly a satisfactorily solution for me, because `epic2` is supposed to be part of a larger computational pipeline.
Anyway, just for the purpose of testing it, I created a new environment just with Python and epic2, but I don't see a change in behavior:

```
$ epic2 --version
0.0.37
[...]
Found a median readlength of 227.0
[...]
Valid ChIP reads: 13363274 (25163171 before out of bounds removal)
[...]
```

**Comment by endrebak** [comment]
I installed epic2 0.0.37 from PyPI:

```
epic2 -c test_set_signal.bedpe -t test_set_control.bedpe -cs chromsizes.txt > /dev/null
Found a median fragment size of 196.5

Using chromosome sizes found in chromsizes.txt.

Using an effective genome length of ~2221 * 1e6

Parsing ChIP file(s):
  test_set_control.bedpe

Valid ChIP reads: 99561 (99561 before out of bounds removal)

Score threshold: 9.447000000000001

Number of tags in a window: 1

Number of islands found: 13798

Parsing Input file(s):
  test_set_signal.bedpe

Valid Background reads: 97392 (97392 before out of bounds removal)
```

Might something be stale on your end?

I'll look more into the binary incompatibility and why it happens. I would rather avoid having to ship epic2 with htslib headers, but it might be the simplest fix to avoid this.

**Comment by ptrebert** [comment]
Hm, ok, I installed via bioconda - is there something wrong with the conda recipe?
I just tested with a plain Python environment, and the `pip install` fails due missing dependencies (pysam pops up first), that should also be fixed...

**Comment by endrebak** [comment]
epic2 requires pysam to be installed before epic2 can be installed. This is because epic2 needs to use pysam functionality in the setup.py file. I'll think about ways to do this better. I should also update the README to `pip install pysam` first :)
