### ISSUE TITLE
Duplicate tool name

### ISSUE THREAD

**Issue by rspreafico** [biocore-ntnu/epic2#3]
Congratulations for this effort, eagerly looking forward to the first release. There seems to be another [SICER2 tool](https://github.com/bioinf/SICER2) which may cause confusion when users will refer to `SICER2`.

**Comment by endrebak** [comment]
It is already working if you would like to try it out. The only reason I have not added it to any package managers is that I might not get to use the name SICER2 and will have to use epic2 instead. The other tool does not seem to be finished though and the repo has not been updated in 2 years. 

Thanks for the feedback anyways :)

**Comment by endrebak** [comment]
I changed the name to epic2 :) Thanks again :)
