### ISSUE TITLE
epic2 run error - Expected 72 from C header, got 88 from PyObject

### ISSUE THREAD

**Issue by mbassalbioinformatics** [biocore-ntnu/epic2#31]
Hi
After installing epic2, when attempting to run just a version check i get the following

```
/home/m/anaconda2/envs/python3_velocyto/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: pysam.libcalignedsegment.PileupColumn size changed, may indicate binary incompatibility. Expected 72 from C header, got 88 from PyObject
  return f(*args, **kwds)
```

Thoughts?

**Comment by endrebak** [comment]
I hear that a lot. I will have to ask on the bioconda issues page. Will do it tomorrow. For now a fix is to create a new environment and install epic2 there.

Or you could try `conda uninstall pysam; conda uninstall epic2; conda install epic2` but that might delete more packages than you hoped to do.

**Comment by endrebak** [comment]
From epic2 0.0.40 and onwards, this should never be a problem. Uploading to bioconda now :)
