### ISSUE TITLE
Start positions all end in 00

### ISSUE THREAD

**Issue by melemieux** [biocore-ntnu/epic2#33]
Hi,

I notice that all the peak Start positions end in "00" (including in your own examples). How is that possible?

Here's my command using epic2 v.0.0.41 under Ubuntu 18.04:
epic2 --treatment input_rmdup.bam --control control_rmdup.bam --genome mm10 --mapq 10 --output test.bed

Thanks,
Madeleine

**Comment by melemieux** [comment]
I've just re-read the description of the parameters so I see that the bin size is causing this behaviour. Can I set the bin size to 1 to increase the position resolution? 

I guess I'll try!

**Comment by endrebak** [comment]
Thanks for creating an issue! No, epic2 is a great caller for diffusely spread out histone modifications, but the minimum recommended bin size is 50. If you require basepair resolution you should try something else like macs2 :)
