### ISSUE TITLE
epic2 ran as normal but didn't return outputs

### ISSUE THREAD

**Issue by dcheng1** [biocore-ntnu/epic2#37]
The code I used:

> epic2 -t merge3.bed -c input.bed -gn mm10 -fs 250 -g 800 -fdr 1e-15 > deleteme.txt

What I had on the terminal:

> Found a median readlength of 50.0
>  
> Using genome mm10.
>  
> Using an effective genome length of ~2379 * 1e6
>  
> Parsing ChIP file(s): 
>   sicer/merge3/merge3_no_blacklist.bed 
> 
> Valid ChIP reads: 25666499 (25666499 before out of bounds removal)

But it just kept runing for several hours without returning results.

**Comment by endrebak** [comment]
You allowed 800 gaps. Did you mean 4 (4*200=800)? :)

**Comment by endrebak** [comment]
```
  --gaps-allowed GAPS_ALLOWED, -g GAPS_ALLOWED
                        This number is multiplied by the window size to
                        determine the number of gaps (ineligible windows)
                        allowed between two eligible windows. Must be an
                        integer. Default: 3.
```

**Comment by dcheng1** [comment]
Oh, I see what mean. Thanks for your quick response!

**Comment by endrebak** [comment]
No problem :) That flag differs from the one in SICER :) Would love to hear if it ran as expected now.

**Comment by dcheng1** [comment]
Yes, it ran sucessfuly now. epic2 is indeed much faster than SICER. I manually inspected the peaks called by epic2 and SICER, and they are mostly identical. The only difference is that with the same setting, epic2 called slightly longer peaks compared to SICER, which is okay for me. I think I will incoporate epic2 into my data analysis pipeline.

**Comment by endrebak** [comment]
epic2 uses slightly different defaults (hg19 vs hg18) and different EGS so slightly different results are to be expected 👍 

Feel free to reopen this issue or create another one if you have further questions :)
