### ISSUE TITLE
Missing --guess-bampe argument

### ISSUE THREAD

**Issue by KunFang93** [biocore-ntnu/epic2#40]
Hi,

I was wondering if --guess-bampe argument is deprecated and how could I deal with bampe file. Thanks!

Best,
Kun

**Comment by endrebak** [comment]
Why do you believe it was deprecated? 

That functionality was kindly implemented by HTTP://github.com/alnfedorov. I've never had the chance to use it (nor do I have any bampe files to do so).

**Comment by KunFang93** [comment]
Because I got this error when I am trying to use --guess-bampe, the version of epic2 is 0.0.44
![Screen Shot 2020-09-24 at 10 00 42 AM](https://user-images.githubusercontent.com/15643651/94162956-e7507200-fe4c-11ea-95df-bd8bf06f6bf7.png)

**Comment by endrebak** [comment]
Could you please try 0.0.45?

**Comment by endrebak** [comment]
I just uploaded 0.0.46. Could you try that instead :) ?

**Comment by KunFang93** [comment]
Thanks for your reply! For sure, but I was wondering if I could use conda to update? or I need to install by source?

**Comment by endrebak** [comment]
Conda should work now :)

**Comment by KunFang93** [comment]
Sorry for missing your message! Thanks!:)
