### ISSUE TITLE
bam paired-end support not yet available for epic2 in current conda installation

### ISSUE THREAD

**Issue by daveiles** [biocore-ntnu/epic2#41]
conda update epic2
.......
~/epic2-0.0.46$ epic2 -v
0.0.44
Sun 11Oct20

**Comment by endrebak** [comment]
Thanks for notifying me. Will investigate later today.

**Comment by endrebak** [comment]
Biocondabot usually does this automatically. But now I made a PR by hand: https://github.com/bioconda/bioconda-recipes/pull/24798

**Comment by endrebak** [comment]
Should be out now
