### ISSUE TITLE
`guess_bampe` missing for `epic2-df`

### ISSUE THREAD

**Issue by mzytnicki** [biocore-ntnu/epic2#46]
Whenever I use `epic2-df` (version 0.0.47), I have the following error:

    Traceback (most recent call last):
      File "/home/user/.local/bin/epic2-df", line 332, in <module>
        bins_counts_ko = _main(args)
      File "/home/user/.local/lib/python3.8/site-packages/epic2/main.py", line 35, in _main
        effective_genome_length, chromsizes = egl_and_chromsizes(args)
      File "epic2/src/genome_info.pyx", line 315, in epic2.src.genome_info.egl_and_chromsizes
      File "epic2/src/genome_info.pyx", line 93, in epic2.src.genome_info.find_readlength 
    KeyError: 'guess_bampe'

For instance, the command generated by `epic2-df -ex` leads to the same error.

Correct if I am wrong, but the option `--guess-bampe` is now present in `epic2`, but not in `epic2-df`.
As a result, the key `guess_bampe` is not set in `args` (neither `True` or `False`, simply not set).

Would this be the source of the problem?

Thanks for the help!

**Comment by endrebak** [comment]
I will look into it. Will probably have some time on Friday :) Sounds like your guess is correct.

**Comment by endrebak** [comment]
Thanks for reporting 🙏 

`0.0.48` is out. Does it work now?

**Comment by mzytnicki** [comment]
It seems that the last version for `pip` is still `0.0.47`, so... well... I added manually the missing chunk into the code.
I am not proud of it, but it seems to work fine now!
I tried with and without `--guess-bampe`.

**Comment by endrebak** [comment]
Try pip install epic2 --no-cache-dir

**Comment by mzytnicki** [comment]
Says:

    Requirement already satisfied: epic2 in /home/login/.local/lib/python3.8/site-packages (0.0.47)

And refuse to download version `0.0.48`.

**Comment by endrebak** [comment]
I am sorry to hear! But I suspect that is due to PyPI quirkiness. Here you
see that a non-OS specific version of 0.0.48 is out on PyPI:
https://pypi.org/project/epic2/#files Perhaps bioconda has it?

**Comment by mzytnicki** [comment]
My fault!  I forgot the `--upgrade` flag...
I have now the version `0.0.48`, which works like a charm.
Thanks!
