### ISSUE TITLE
is v0.0.52 available on bioconda?

### ISSUE THREAD

**Issue by tingliu-uhn** [biocore-ntnu/epic2#56]
Hi, I wonder if epic2 v0.0.52 is available on bioconda? We tried both updating and re-installing the epic2 package, but the version was still 0.0.41, and the "--guess-bampe" option that we would like to use seemed unavailable on 0.0.41 version. Our environment is Linux bash 4.2.46(2) with python 3.6. Thanks!

**Comment by tingliu-uhn** [comment]
got the issue fixed, switched into the conda-forge channel and also updated the version of libgcc-ng package, which reported as a conflict

**Comment by endrebak** [comment]
I just upload to PyPI and conda-bot takes care of adding it to bioconda. So
it should be there. I'm happy you found the solution. Hope epic2 works for
your use case :)

**Comment by tingliu-uhn** [comment]
thanks!
