### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Victor21v** [biocore-ntnu/epic2#6]
Hi!

I cannot run the program as I get "Segmentation fault" error while trying to execute it:

epic2 -t Treatment.bam -c Control.bam -gn sacCer3 > Try.txt

"Using an effective genome length of ~9 * 1e6 

Parsing ChIP file(s):
  Treatment.bam

  Valid ChIP reads: 74610

Score threshold: 8.169

Number of tags in a window: 3
Segmentation fault "

Any clue?

Thanks in advance.
Víctor-

**Comment by endrebak** [comment]
Thanks, I have noticed a similar thing on some of my machines. I have attempted to fix it, will see if I can upload a fix today :)

**Comment by endrebak** [comment]
Thanks for bothering to report this. I noticed segfaults happening on macOS, not linux. 

Could you please try `pip install epic2==0.0.11`? If it does not work, please post the output log. If it does work, please tell me :)

**Comment by Victor21v** [comment]
Hi! I will try it as soon as possible. Thanks for the quick response :)
