### ISSUE TITLE
Package available at Conda

### ISSUE THREAD

**Issue by mpaya** [biocore-ntnu/epic2#8]
Hi,I'm trying to use epic2 within a local Galaxy instance, which uses Conda as preferred package manager. Would it be possible to have this package accessible also through Conda, not only Pypi? Thanks! :)

**Comment by endrebak** [comment]
Good idea. I guess epic2 is pretty stable now. I will try to add it within tomorrow :)

**Comment by endrebak** [comment]
I actually tried this more than a month ago, but then something was wrong with the build system. Have tried starting the PR checks again :).

**Comment by mpaya** [comment]
Oh, good luck with that. So far I could get epic2 running through direct install in galaxy with pip, though that is not the recommended way, and the test works. I'll keep an eye here for updates :)

**Comment by endrebak** [comment]
Thanks. I will update epic2 in bioconda soon, I just need to add some of
its newest deps there :)
